apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    name: web-server
    type: app-server
spec:
  containers:
  -  name: nginx
     image: nginx:latest
     resources:
       requests:
         memory: "128Mi"
         cpu: "500m"
       limits:
         memory: "128Mi"
         cpu: "500m"
     ports:
       -  containerPort: 80
