apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper 
  labels:
    name: ubuntu-sleeper
    type: custom-ubuntu
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu:sleeper 
    imagePullPolicy: IfNotPresent
    command: #equivanet of docker ENTRYPOINT
     - sleep 
    args:    #equivalent of docker CMD
     - "2"
