apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    type: testing
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: front-end
    spec:
      containers:
        - name: nginx 
          image: nginx
  replicas: 4
    